### ISSUE TITLE
BookStack Helm chart does’t work

### ISSUE THREAD

**Issue by donjuardo** [gabe565/charts#13]
When I try to access the application in the web browser it just shows a blank page. I followed the instructions in the README

**Comment by gabe565** [comment]
@duardos I use the chart and haven't had issues, but let me spin up an instance with the default values to make sure all of the defaults are correct. Did you change any of the values?

**Comment by gabe565** [comment]
@donjuardo Hey! Were you able to get the Bookstack chart deployed? I'm still happy to help, but I'll close this ticket if I don't hear back in the next week or so.

**Comment by gabe565** [comment]
Feel free to reopen if you're still having deployment issues!
