### ISSUE TITLE
Switch to a maintained fork of Hammond

### ISSUE THREAD

**Issue by djjudas21** [gabe565/charts#281]
### Chart Name

hammond

### Chart Version

0.5.1

### Bug Description

Hey, thanks for maintaining these awesome charts.

Just wanted to let you know that the [akhilrex/hammond](https://github.com/akhilrex/hammond) project [has been abandoned](https://github.com/akhilrex/hammond/issues/81) but there is an active fork called [alfhou/hammond](https://github.com/alfhou/hammond/) which is actively maintained.

I have been maintaining [my own Helm chart](https://github.com/djjudas21/charts/tree/main/charts/hammond) for the alfhou fork, but if you wanted to update your Helm chart to point at `alfhou/hammond:v0.0.21` that would be awesome. The projects are compatible so no other work is needed.

**Comment by gabe565** [comment]
@djjudas21 Thanks for the heads up! I've noticed that Hammond hasn't gotten an update in a while, but I haven't had a chance to see if there were any active forks. I'll verify no other config needs to change, then I'll push that shortly 🙂
