### ISSUE TITLE
accessMode is required

### ISSUE THREAD

**Issue by cnu80** [gabe565/charts#489]
### Chart Name

paperless

### Chart Version

0.11.0

### Bug Description

I tried to install paperless with your chart and I got the error message:
```
helm install paperless-ngx oci://ghcr.io/gabe565/charts/paperless-ngx
Pulled: ghcr.io/gabe565/charts/paperless-ngx:0.11.0
Digest: sha256:b0c5247e3c1d6b9f1b1fff2a389dd6218636685787d258b53b4fa060da94719b
Error: INSTALLATION FAILED: execution error at (paperless-ngx/templates/common.yaml:50:3): accessMode is required for PVC paperless-ngx-consume
```

### values.yaml

```yaml
everything default
```

**Comment by gabe565** [comment]
That's because `accessMode` is a required field by the upstream common chart. In this case, you'll need to set `persistence.consume.accessMode` to `ReadWriteOnce`, `ReadWriteMany`, etc.

**Comment by cnu80** [comment]
Thanks, I thought it is a fire and forget command ... ;-). 
With a configured values.yaml it is working.
