### ISSUE TITLE
Doing PostgreSQL Upgrades with Paperless-Ngx

### ISSUE THREAD

**Issue by Cogitri** [gabe565/charts#547]
### Chart Name

paperless-ngx

### Chart Version

0.15.1

### Problem

Doing upgrades of Postgres is a bit tedious currently, since one has to:

* Dump the DB with the old Postgres-Version
* Start the old Postgres-Pod with `diagnosticMode.enabled=True`
* Move/Delete the old datadir
* Start the Postgres-Pod with the new version with `diagnosticMode.enabled=False` while making sure that Paperless doesn't connect to the DB. Import the DB dump. Only afterwards should paperless reconnect

Nextclould has a maintenance mode for that which makes sure that it doesn't write to the DB. Since Paperless doesn't offer that, maybe it'd be possible to expose a `diagnosticMode` in the Paperless-ngx Chart as well which just sleeps for ever?

I first tried to shutdown Paperless with `kubectl scale`, but upon doing `helm upgrade` to apply the `diagnosticMode` for Postgres, Paperless was started again. But maybe there's some other more elegant way to do it. Thanks as always for providing the Chart! :)

**Comment by gabe565** [comment]
@Cogitri Yeah, major Postgres bumps are always frustrating. Could try setting:
```yaml
controller:
  replicas: 0
```
and try again?

**Comment by Cogitri** [comment]
Yeah that works, thanks!
