### ISSUE TITLE
Support for cronjob with bookstack

### ISSUE THREAD

**Issue by nerok** [gabe565/charts#59]
Hi,
I want to run the copy-shelf-permission(https://www.bookstackapp.com/docs/admin/commands/#copy-shelf-permission) command on bookstack, and this seems best done with a cronjob on the side of the deployment. At this point I just created it manually, but it would be nice to add it to the helmchart, either as "additionalResources" or specifically as additional cronjobs.

**Comment by gabe565** [comment]
@nerok Hi! Thanks for reaching out.  
Cron jobs are supported in the linuxserver container that my chart uses. I'll investigate and add some docs for that. Do you think that would suffice or would an actual CronJob resource be more useful? Personally, I'd prefer to use an actual CronJob, but the built in cron instance would be much simpler and probably less prone to breaking.

**Comment by nerok** [comment]
Thanks for the quick response :D
Will the internal cronjob be able to alert anywhere if it fails? I agree that it could work, but I prefer to use the cronjob resource as it will be picked up by Prometheus if it fails. I also think it is best pratice to have cronjob externally, since if you have multiple replicas, all replicas would run the cronjob.

**Comment by gabe565** [comment]
You're welcome! You had a good point that CronJobs are more observable, so the added complexity is worth it.

I just released v0.6.0 of the Bookstack chart which adds a CronJob for this!
It is disabled by default. To enable it, you will have to set `shelfPermissionsCron.enabled=true`.

Here are the new values available:
| Key | Type | Default | Description |
|-----|------|---------|-------------|
| shelfPermissionsCron.command | list | See [values.yaml](https://github.com/gabe565/charts/blob/main/charts/bookstack/values.yaml#L69-L76) | Shelf permissions CronJob command |
| shelfPermissionsCron.controller.cronjob.schedule | string | `"0 0 * * *"` | Shelf permissions CronJob time |
| shelfPermissionsCron.enabled | bool | `false` | Enables a CronJob that copies shelf permissions to all child books.    [[ref]](https://bookstackapp.com/docs/admin/commands/#copy-shelf-permission) |
| shelfPermissionsCron.nameOverride | string | `"copy-shelf-permissions"` | Shelf permissions CronJob name |

Let me know if you have any questions 🙂

**Comment by nerok** [comment]
Sweet, thank you very much 👍

**Comment by gabe565** [comment]
@nerok CronJob has been working on my end, so I'm going to close this issue. Feel free to reopen if you have any issues!
