### ISSUE TITLE
Flame Kubernetes integration doesn't work when RBAC is enabled

### ISSUE THREAD

**Issue by djjudas21** [gabe565/charts#652]
### Chart Name

flame

### Chart Version

flame-0.5.4

### Bug Description

The [Kubernetes integration within Flame](https://github.com/pawelmalak/flame?tab=readme-ov-file#kubernetes-integration) works by polling all Ingress resources for specific annotations, and adding links to those ingresses to its dashboard.

On a cluster with RBAC enabled, this results in Flame failing to add these ingresses, and repeatedly logging this error:

```
[2024-07-16 15:13:28.465 UTC+0] [ERROR] Can't connect to the Kubernetes API
```

This requires some extra RBAC permissions to allow Flame to list and get ingresses. At a minimum, this chart will need to provide:
* ServiceAccount
* ClusterRole
* ClusterRoleBinding

I'm just trying to figure out what the specific permissions are, and I hope to submit a PR soon.

**Comment by gabe565** [comment]
@djjudas21 Oh I hadn't seen the Kubernetes integration yet! That's awesome. So, the library chart I use can create a ServiceAccount with
```
serviceAccount:
  create: true
```
but we'll need to add the ClusterRole and ClusterRolebinding like you mentioned.

The Flame source code makes it look like it'll only need permission to list ingresses: https://github.com/pawelmalak/flame/blob/3c347c854c4c55456785ff026a703422d8f02f62/controllers/apps/docker/useKubernetes.js#L16C30-L16C34

**Comment by gabe565** [comment]
@djjudas21 Oh haha you already made a PR 🤦 taking a look at it now
