### ISSUE TITLE
[obico] deepCopy errors if no env values are provided

### ISSUE THREAD

**Issue by tvories** [gabe565/charts#67]
I believe there needs to be a wrapper around the `deepCopy` blocks in the template to test whether or not `.Values.server.env` are provided.  I did not provide any server environment variables, and I am receiving the following error:

```
Helm install failed: template: obico/templates/server.yaml:84:9: executing "obico/templates/server.yaml" at <include "obico.server.hardcodedValues" .>: error calling include: template: obico/templates/server.yaml:27:12: executing "obico.server.hardcodedValues" at <deepCopy .Values.server.env>: error calling deepCopy: reflect: call of reflect.Value.Type on zero Value Last Helm logs:
```

When I add a value, the error goes away: https://github.com/tvories/k8s-gitops/commit/72ab9f50d1a2647d694e34a847e88341f173fff2

I believe the issue can be solved by changing [Line 27 in templates/server.yaml](https://github.com/gabe565/charts/blob/b189e5985e1f1edcb854848064315264517649c0/charts/obico/templates/server.yaml#L27) from

```yaml
{{- $env := deepCopy .Values.server.env }}
```

to

```yaml
{{- if .Values.server.env }}
{{- $env = deepCopy .Values.server.env }}
{{- end }}
```
There are a few deepCopy blocks that may benefit from wrapping them in a test to see if the values are defined.

**Comment by gabe565** [comment]
Ah good point. I originally had some default values so I didn't worry about checking if it was null, but removed them at the last second 🤦 Fixing it now!

**Comment by gabe565** [comment]
Ok, I'm releasing v0.0.2 which fixes this!

I ended up using a default value before the deepCopy. So this:
```go
{{- $env := deepCopy .Values.server.env }}
```
became this
```go
{{- $env := default dict .Values.server.env | deepCopy }}
```

**Comment by tvories** [comment]
Someone else in the k8s discord mentioned supporting envFrom as well. Not sure if that needs a change or not

**Comment by gabe565** [comment]
Thanks, I just joined the Discord and posted in that channel 🙂
